id: IA28FDED3
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-4989
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 15:14:47.407100+00:00
last_modified: 2023-09-28 15:14:47.407106+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23849
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23849
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པའི་རྒྱན།
  languages:
  - bo
  author: རིག་པའི་དབང་ཕྱུག་དགེ་བ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9988245437766173
  ocr_word_median_confidence_index: 1.0
bases:
  I1CZ2530:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2530
      total_pages: 472
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2530.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9988245437766173
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
